name: build-and-deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          MODE: production

      - name: Test
        run: npm test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs